name: Create or update a repository secret

on:
  workflow_dispatch:
    inputs:
      repository:
        type: choice
        options:
          - repo_one
          - repo_two
        required: true
        description: Repository for secret
        default: repo_one
        
      secret_name:
        type: text
        required: true
        description: Secret name
        
      secret_value:
        type: text
        required: true
        description: Secret value
        
jobs:
  create_or_update_secret:
    name: Create or Update Secret
    
    runs-on: ubuntu-20.04
    
    steps:
      - name: Mask the secret value
        run: |
          echo "::add-mask::${{ github.event.inputs.secret_value }}"
      
      - name: Get temporay application token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
        
      - name: Checkout secret maanger action
        uses: actions/checkout@v3
        with:
          repository: peter-murray/github-secrets-manager-action
          ref: main
          path: github-secrets-manager-action
          
      - name: Create or update secret
        uses: ./github-secrets-manager-action/create-or-update-secret
        with:
          github_token: ${{ steps.get_workflow_token.outputs.token }}
          repository: ${{ github.event.inputs.repository }}
          secret: ${{ github.event.inputs.secret_name }}
          value: ${{ github.event.inputs.secret_value }}
          
      
      
